### ISSUE TITLE
needs a release allowing blaze-builder-0.4.*

### ISSUE THREAD

**Issue by simonmichael** [meiersi/blaze-builder-enumerator#4]

**Comment by snoyberg** [comment]
Relevant Stackage issue: https://github.com/fpco/stackage/issues/442

It may be possible to take advantage of streaming-commons, which has a compatibility layer in place for the blaze-builder 0.3/0.4 switch.

**Comment by manny-fp** [comment]
Pull request: #5

**Comment by meiersi** [comment]
Released: http://hackage.haskell.org/package/blaze-builder-enumerator-0.2.0.7
